"""Built-in bootstrap pack: the out-of-the-box release (authored, not ingested).

Data only — loading/merging logic lives in releases.py. The `families`
allowlist here is the reviewed generator set shipped with the backend.
"""
from __future__ import annotations

from typing import Any

BOOTSTRAP_RELEASE: dict[str, Any] = {
    "release_id": "grove-bootstrap",
    "version": "0.1.0",
    "generated_at": "2026-09-19T00:00:00+00:00",
    "approved": True,
    "source": "built-in bootstrap pack (authored, not ingested)",
    "concepts": [
        {
            "id": "concept.percentages-basics",
            "skill_id": "quant.frp.percentages",
            "title": "Percentages",
            "summary": "A percentage is a fraction of 100. x% of N = (x/100) × N. To reverse: x is what percent of N → (x/N) × 100.",
            "formulas": [
                "x% of N = x/100 × N",
                "Percent change = (new − old)/old × 100",
                "Successive change of a% then b% = a + b + ab/100",
            ],
            "worked_example": "What is 35% of 240? 35/100 × 240 = 84. A price rises from 200 to 250: change = 50/200 × 100 = 25% increase.",
            "common_mistakes": [
                "Treating a 20% decrease followed by a 20% increase as net zero (it is a 4% net decrease).",
                "Using the new value as the base when computing percent change.",
            ],
            "related_families": ["percent.of", "percent.change"],
        },
        {
            "id": "concept.ratios-basics",
            "skill_id": "quant.frp.ratios",
            "title": "Ratios and proportions",
            "summary": "A ratio a:b divides a whole into a+b parts. One part = total/(a+b). Proportions state two ratios are equal: a/b = c/d.",
            "formulas": [
                "One part = total / (sum of ratio terms)",
                "a/b = c/d ⇒ ad = bc",
            ],
            "worked_example": "₹540 divided in 2:3:4 → 9 parts → one part = 60 → shares 120, 180, 240.",
            "common_mistakes": ["Adding ratio terms after scaling one of them.", "Forgetting all parts must use the same unit."],
            "related_families": ["ratio.split"],
        },
        {
            "id": "concept.averages-basics",
            "skill_id": "quant.avg.averages",
            "title": "Averages",
            "summary": "Average = sum of values / count. Sum = average × count. A weighted average blends group averages by size.",
            "formulas": [
                "Average = Σx / n",
                "Weighted average = Σ(nᵢ·aᵢ) / Σnᵢ",
            ],
            "worked_example": "The average of 6 numbers is 40. Five of them sum to 190, so the sixth is 240 − 190 = 50.",
            "common_mistakes": ["Assuming the missing value equals the average.", "Mixing up count and sum in weighted problems."],
            "related_families": ["averages.missing", "averages.weighted"],
        },
        {
            "id": "concept.simple-interest",
            "skill_id": "quant.avg.simple_interest",
            "title": "Simple and compound interest",
            "summary": "Simple interest grows linearly: SI = PRT/100. Compound interest grows on accrued amount each period.",
            "formulas": [
                "SI = P·R·T / 100",
                "Amount (compound) = P(1 + R/100)^T",
                "CI = Amount − P",
            ],
            "worked_example": "₹8,000 at 10% for 2 years: SI = 1600; CI = 8000(1.1²) − 8000 = 1680.",
            "common_mistakes": ["Using SI formula for compound questions.", "Forgetting to subtract the principal for CI."],
            "related_families": ["interest.simple", "interest.compound"],
        },
        {
            "id": "concept.time-work",
            "skill_id": "quant.tws.time_work",
            "title": "Time and work",
            "summary": "Rates add. If A finishes a job in a hours, A's rate is 1/a per hour; together the time is ab/(a+b).",
            "formulas": ["Combined time = a·b / (a + b) for two workers", "Rate = 1 / time"],
            "worked_example": "A in 12 h, B in 24 h → together 12·24/36 = 8 hours.",
            "common_mistakes": ["Adding times instead of rates.", "Forgetting to invert the combined rate back into time."],
            "related_families": ["time_work.together"],
        },
        {
            "id": "concept.number-series",
            "skill_id": "logic.pat.number_series",
            "title": "Number series",
            "summary": "Check for constant difference (arithmetic), constant ratio (geometric), alternating rules, or second-order differences.",
            "formulas": ["Arithmetic: tₙ = a + (n−1)d", "Geometric: tₙ = a·rⁿ⁻¹"],
            "worked_example": "4, 9, 14, 19, … → +5 each time → next is 24.",
            "common_mistakes": ["Assuming a rule from only two terms.", "Missing alternating sequences."],
            "related_families": ["series.arith_next", "series.geo_next", "series.alternating"],
        },
        {
            "id": "concept.blood-relations",
            "skill_id": "logic.rel.blood_relations",
            "title": "Blood relations",
            "summary": "Draw a small family tree while reading. Resolve generation by generation; never assume gender unless stated.",
            "formulas": [],
            "worked_example": "\"My grandfather's only son\" = my father; his daughter = my sister.",
            "common_mistakes": ["Skipping a generation.", "Assuming gender from names."],
            "related_families": ["relations.simple"],
        },
        {
            "id": "concept.coding-decoding",
            "skill_id": "logic.code.coding_decoding",
            "title": "Coding-decoding",
            "summary": "Compare the given word with its code letter-by-letter to find the shift or substitution rule, then apply it to the probe word.",
            "formulas": ["Caesar shift: letter → letter + k (mod 26)"],
            "worked_example": "If CAT → DBU, each letter shifts +1, so SUN → TVO.",
            "common_mistakes": ["Applying the rule backwards (−k instead of +k).", "Mixing position-shift and letter-swap rules."],
            "related_families": ["coding.shift", "coding.symbol"],
        },
    ],
    "flashcards": [
        {"id": "fc.pct-1", "skill_id": "quant.frp.percentages", "front": "x% of N = ?", "back": "(x/100) × N"},
        {"id": "fc.pct-2", "skill_id": "quant.frp.percent_change", "front": "Percent change formula", "back": "(new − old)/old × 100"},
        {"id": "fc.ratio-1", "skill_id": "quant.frp.ratios", "front": "One part of ratio a:b:c from total T", "back": "T / (a+b+c)"},
        {"id": "fc.avg-1", "skill_id": "quant.avg.averages", "front": "Sum from average", "back": "sum = average × count"},
        {"id": "fc.si-1", "skill_id": "quant.avg.simple_interest", "front": "Simple interest", "back": "SI = P·R·T/100"},
        {"id": "fc.ci-1", "skill_id": "quant.avg.compound_interest", "front": "Compound amount", "back": "P(1 + R/100)^T; CI = amount − P"},
        {"id": "fc.tw-1", "skill_id": "quant.tws.time_work", "front": "Two workers together (a h, b h)", "back": "ab/(a+b) hours"},
        {"id": "fc.series-1", "skill_id": "logic.pat.number_series", "front": "First checks for a series", "back": "Difference → ratio → alternating → second differences"},
        {"id": "fc.rel-1", "skill_id": "logic.rel.blood_relations", "front": "Best first step for blood relations", "back": "Draw a family tree, generation by generation"},
        {"id": "fc.code-1", "skill_id": "logic.code.coding_decoding", "front": "Caesar shift decoding", "back": "Compare word vs code letter-by-letter; find constant shift k"},
    ],
    # Families allowed in tests, with skill + difficulty mix. Templates are the
    # deterministic generators shipped with the backend (reviewed code).
    "families": [
        {"family_id": "arith.multiply", "skill_id": "quant.numbers.arithmetic", "difficulties": ["direct", "multi_step", "transfer"]},
        {"family_id": "divisibility.remainder", "skill_id": "quant.numbers.divisibility", "difficulties": ["direct", "multi_step"]},
        {"family_id": "divisibility.count", "skill_id": "quant.numbers.divisibility", "difficulties": ["direct", "multi_step"]},
        {"family_id": "factors.count", "skill_id": "quant.numbers.factors_multiples", "difficulties": ["direct", "multi_step"]},
        {"family_id": "hcf_lcm.basic", "skill_id": "quant.numbers.hcf_lcm", "difficulties": ["direct", "multi_step"]},
        {"family_id": "numbers.power_cycle", "skill_id": "quant.numbers.power_cycles", "difficulties": ["multi_step", "transfer"]},
        {"family_id": "percent.of", "skill_id": "quant.frp.percentages", "difficulties": ["direct", "multi_step"]},
        {"family_id": "percent.change", "skill_id": "quant.frp.percent_change", "difficulties": ["direct", "multi_step", "transfer"]},
        {"family_id": "ratio.split", "skill_id": "quant.frp.ratios", "difficulties": ["direct", "multi_step"]},
        {"family_id": "fractions.compare", "skill_id": "quant.frp.fractions", "difficulties": ["direct", "multi_step"]},
        {"family_id": "averages.missing", "skill_id": "quant.avg.averages", "difficulties": ["direct", "multi_step"]},
        {"family_id": "averages.weighted", "skill_id": "quant.avg.averages", "difficulties": ["multi_step"]},
        {"family_id": "mixtures.alligation", "skill_id": "quant.avg.mixtures", "difficulties": ["multi_step"]},
        {"family_id": "profit_loss.basic", "skill_id": "quant.avg.profit_loss", "difficulties": ["direct", "multi_step"]},
        {"family_id": "interest.simple", "skill_id": "quant.avg.simple_interest", "difficulties": ["direct", "multi_step"]},
        {"family_id": "interest.compound", "skill_id": "quant.avg.compound_interest", "difficulties": ["multi_step"]},
        {"family_id": "time_work.together", "skill_id": "quant.tws.time_work", "difficulties": ["direct", "multi_step"]},
        {"family_id": "speed.basic", "skill_id": "quant.tws.speed_distance_time", "difficulties": ["direct"]},
        {"family_id": "speed.harmonic", "skill_id": "quant.tws.speed_distance_time", "difficulties": ["multi_step", "transfer"]},
        {"family_id": "ages.simple", "skill_id": "quant.alg.ages", "difficulties": ["direct", "multi_step"]},
        {"family_id": "equations.linear", "skill_id": "quant.alg.equations", "difficulties": ["direct", "multi_step"]},
        {"family_id": "series.arith_next", "skill_id": "logic.pat.number_series", "difficulties": ["direct", "multi_step"]},
        {"family_id": "series.geo_next", "skill_id": "logic.pat.number_series", "difficulties": ["direct", "multi_step"]},
        {"family_id": "series.alternating", "skill_id": "logic.pat.number_series", "difficulties": ["multi_step", "transfer"]},
        {"family_id": "series.letters", "skill_id": "logic.pat.letter_series", "difficulties": ["direct", "multi_step"]},
        {"family_id": "relations.simple", "skill_id": "logic.rel.blood_relations", "difficulties": ["direct", "multi_step", "transfer"]},
        {"family_id": "syllogism.basic", "skill_id": "logic.rel.syllogisms", "difficulties": ["direct", "multi_step"]},
        {"family_id": "directions.triples", "skill_id": "logic.rel.directions", "difficulties": ["direct", "multi_step"]},
        {"family_id": "arrangement.ordering", "skill_id": "logic.arr.ordering", "difficulties": ["direct", "multi_step"]},
        {"family_id": "arrangement.seating", "skill_id": "logic.arr.seating", "difficulties": ["multi_step"]},
        {"family_id": "coding.shift", "skill_id": "logic.code.coding_decoding", "difficulties": ["direct", "multi_step"]},
        {"family_id": "coding.symbol", "skill_id": "logic.code.symbol_substitution", "difficulties": ["direct"]},
        {"family_id": "classification.odd_one_out", "skill_id": "logic.code.classification", "difficulties": ["direct"]},
    ],
    "source_refs": [],
}
